application: iosport-exotics-engine
version: 1
runtime: python27
api_version: 1
threadsafe: false
libraries:
- name: yaml
  version: latest
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^dev
- ^fabfile.py
- ^README
- ^tmp
handlers:
# STATIC
- url: /css
  static_dir: css
- url: /js
  static_dir: js
# API
- url: /api/hello.*
  script: controllers.api.hello.app
# SCRAPERS
- url: /tasks/scrapers/bbc/fixtures.*
  script: tasks.scrapers.bbc.fixtures.app
# DEFAULT
- url: /.*
  script: controllers.demo.root.app
