application: iosport-exotics-engine
version: 1
runtime: python27
api_version: 1
threadsafe: false
libraries:
- name: yaml
  version: latest
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^dev
- ^fabfile.py
- ^README
- ^tmp
handlers:
# STATIC
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
# APP
- url: /app.*
  script: controllers.app.app
# TASKS
- url: /tasks/bbc_fixtures.*
  script: tasks.bbc_fixtures.app
- url: /tasks/random/season_match_bets.*
  script: tasks.random.season_match_bets.app
- url: /tasks/random/single_team_outrights.*
  script: tasks.random.single_team_outrights.app
- url: /tasks/blobs/outright_payoffs.*
  script: tasks.blobs.outright_payoffs.app
- url: /tasks/blobs/smb_versus.*
  script: tasks.blobs.smb_versus.app
- url: /tasks/yc_probabilities.*
  script: tasks.yc_probabilities.app
# ROOT
- url: .*
  script: controllers.root.app 