application: iosport-exotics-engine
version: 1
runtime: python27
api_version: 1
threadsafe: false
libraries:
- name: yaml
  version: latest
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^dev
- ^fabfile.py
- ^README
- ^tmp
handlers:
# STATIC
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
# APP
- url: /app/bets.*
  script: controllers.app.bets.app
- url: /app/blobs.*
  script: controllers.app.blobs.app
- url: /app/expiries.*
  script: controllers.app.expiries.app
- url: /app/products.*
  script: controllers.app.products.app
- url: /app.*
  script: controllers.app.app
# TASKS
- url: /tasks/blobs/bets/outright_payoffs.*
  script: tasks.blobs.bets.outright_payoffs.app
- url: /tasks/blobs/bets/smb_versus.*
  script: tasks.blobs.bets.smb_versus.app
- url: /tasks/blobs/matches.*
  script: tasks.blobs.matches.app
- url: /tasks/blobs/teams.*
  script: tasks.blobs.teams.app
- url: /tasks/quant/bbc_fixtures.*
  script: tasks.quant.bbc_fixtures.app
- url: /tasks/quant/dc_poisson_means.*
  script: tasks.quant.dc_poisson_means.app
- url: /tasks/quant/yc_probabilities.*
  script: tasks.quant.yc_probabilities.app
# ROOT
- url: .*
  script: controllers.root.app 