application: iosport-exotics-engine
version: 1
runtime: python27
api_version: 1
threadsafe: false
libraries:
- name: yaml
  version: latest
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^dev
- ^fabfile.py
- ^README
- ^tmp
handlers:
# STATIC
- url: /css
  static_dir: css
- url: /js
  static_dir: js
# API
- url: /api/leagues.*
  script: controllers.api.leagues.app
- url: /api/pricing/mini_leagues.*
  script: controllers.api.pricing.mini_leagues.app
- url: /api/pricing/single_teams.*
  script: controllers.api.pricing.single_teams.app
# TASKS
- url: /tasks/bbc_fixtures.*
  script: tasks.bbc_fixtures.app
- url: /tasks/yc_probabilities.*
  script: tasks.yc_probabilities.app
# DEFAULT
- url: /.*
  script: controllers.demo.root.app
