#application: iosport-exotics-engine-177508
#version: 1
runtime: python27
api_version: 1
threadsafe: false
libraries:
- name: yaml
  version: latest

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^dev
- ^fabfile.py
- ^README
#- ^tmp
- ^\.git/.*$
- ^\.idea/.*$
- ^js/app/node_modules

handlers:
# STATIC
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
# APP
- url: /api/exotic_accas.*
  script: controllers.api.exotic_accas.app
- url: /api/fixtures.*
  script: controllers.api.fixtures.app
- url: /app.*
  script: controllers.api.app
# TASKS
- url: /tasks/fixtures.*
  script: tasks.fixtures.app
- url: /tasks/results.*
  script: tasks.results.app
# ROOT
- url: .*
  script: controllers.root.app

