- id: 118996114
  raw_name: Premier League
  name: ENG.1
- id: 118996115
  raw_name: Championship
  name: ENG.2
- id: 118996116
  raw_name: League One
  name: ENG.3
- id: 118996117
  raw_name: League Two
  name: ENG.4
- id: 119000981
  raw_name: French Ligue 1
  name: FRA.1
- id: 119000986
  raw_name: German Bundesliga
  name: GER.1
- id: 119001074
  raw_name: Spanish La Liga
  name: SPA.1
