- label: "Single Team Outright"
  type: "single_team_outright"
  description: "An outright bet on a single team, <b>but with dozens of different payoffs!</b>"
  form: "SingleTeamOutrightForm"
  class: "SingleTeamOutrightBet"
- label: "Season Match Bet"
  type: "season_match_bet"
  description: "Bet on your favorite team to finish ahead of their hated rival!"
  form: "SeasonMatchBetForm"
  class: "SeasonMatchBet"
- label: "Mini League"
  type: "mini_league"
  description: "Construct your own virtual mini league of teams from different countries and divisions!<br/><br/><b>Note that a mini- league starts all teams from today on zero points and does not use current league position!</b>"
  form: "MiniLeagueForm"
  class: "MiniLeagueBet"
- label: "Exotic Acca"
  type: "exotic_acca"
  description: "An acca in which not every team has to win to get paid - <b>select how many teams you want to win or lose, and by how many goals!</b>"
  form: "ExoticAccaForm"
  class: "ExoticAccaBet"