- label: "Single Team Outright"
  type: "single_team_outright"
  description: "An outright bet on a single team, but with dozens of different payoffs!"
  form: "SingleTeamOutrightForm"
  class: "SingleTeamOutrightBet"
- label: "Season Match Bet"
  type: "season_match_bet"
  description: "Bet on your favorite team to finish ahead of their hated rival!"
  form: "SeasonMatchBetForm"
  class: "SeasonMatchBet"
- label: "Mini League"
  type: "mini_league"
  description: "Construct your own virtual mini league of teams from different countries and divisions!"
  form: "MiniLeagueForm"
  class: "MiniLeagueBet"